apiVersion: v1
kind: Service
metadata:
  name: k8s-test-svc
  labels:
    app: k8s-test
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30050 #暴露端口类似docker容器的端口映射，将本地的30050 -> 8080
  selector:
    app: k8s-test